/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import bo.Question;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import service.Database;

/**
 *
 * @author aditya
 */
public class AddQues extends javax.swing.JInternalFrame {

    private Database db = ApplicationRunner.getDatabase();
    private Question ques = new Question();

    private int qid = 0, ans = 0, diff_level = 0;
    private String question, option1, option2, option3, option4;

    private ButtonGroup bg1 = new ButtonGroup();
    private ButtonGroup bg2 = new ButtonGroup();

    /**
     * Creates new form AddQues
     */
    public AddQues() {
        initComponents();

        bg1.add(opt1);
        bg1.add(opt2);
        bg1.add(opt3);
        bg1.add(opt4);

        bg2.add(low_l);
        bg2.add(med_l);
        bg2.add(high_l);

        setQidlabel();
    }

    private void setQidlabel() {
        if (db.getQid() > 0) {
            if (ques.getQid() != db.getQid()) {
                ques.setQid(db.getQid());
            }
        } else {
            ques.setQid(0);
        }
        jLabel_qid.setText(Integer.toString(ques.getQid() + 1));
    }

    private boolean checkall() {
        if (qid >= 0 && ans != 0 && diff_level != 0 && !question.equals("") && !option1.equals("") && !option2.equals("") && !option3.equals("") && !option4.equals("")) {
            return true;
        }
        return false;

    }

    private void addtoques() {
        ques.setQuestion(question);
        ques.setOption1(option1);
        ques.setOption2(option2);
        ques.setOption3(option3);
        ques.setOption4(option4);
        ques.setAns(ans);
        ques.setDiff(diff_level);
        ques.setQid(ques.getQid() + 1);
        db.insertQues(ques);
    }

    private void AddData() {
        question = get_question.getText();
        option1 = get_opt1.getText();
        option2 = get_opt2.getText();
        option3 = get_opt3.getText();
        option4 = get_opt4.getText();

        if (low_l.isSelected()) {
            diff_level = 1;
        } else if (med_l.isSelected()) {
            diff_level = 2;
        } else if (high_l.isSelected()) {
            diff_level = 3;
        }

        if (opt1.isSelected()) {
            ans = 1;
        } else if (opt2.isSelected()) {
            ans = 2;
        } else if (opt3.isSelected()) {
            ans = 3;
        } else if (opt4.isSelected()) {
            ans = 4;
        }
    }

    private void reset() {
        get_question.setText("");
        get_opt1.setText("");
        get_opt2.setText("");
        get_opt3.setText("");
        get_opt4.setText("");
        bg1.clearSelection();
        bg2.clearSelection();
        setQidlabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        get_opt4 = new javax.swing.JTextField();
        submit_ques = new javax.swing.JButton();
        Qid_label = new javax.swing.JLabel();
        opt1 = new javax.swing.JRadioButton();
        opt2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        opt3 = new javax.swing.JRadioButton();
        Leveldiff = new javax.swing.JLabel();
        opt4 = new javax.swing.JRadioButton();
        low_l = new javax.swing.JRadioButton();
        med_l = new javax.swing.JRadioButton();
        high_l = new javax.swing.JRadioButton();
        get_question = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ansopt = new javax.swing.JLabel();
        get_opt1 = new javax.swing.JTextField();
        opt1_label = new javax.swing.JLabel();
        get_opt2 = new javax.swing.JTextField();
        opt2_label = new javax.swing.JLabel();
        opt3_label = new javax.swing.JLabel();
        get_opt3 = new javax.swing.JTextField();
        opt4_label = new javax.swing.JLabel();
        jLabel_qid = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        get_opt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_opt4ActionPerformed(evt);
            }
        });

        submit_ques.setText("Submit Question");
        submit_ques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_quesActionPerformed(evt);
            }
        });

        Qid_label.setText("Give Question ID :");

        opt1.setText("Option1");
        opt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1ActionPerformed(evt);
            }
        });

        opt2.setText("Option2");
        opt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setText("Add Question");

        opt3.setText("Option3");
        opt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3ActionPerformed(evt);
            }
        });

        Leveldiff.setText("* Select difficulty of question :");

        opt4.setText("Option4");
        opt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4ActionPerformed(evt);
            }
        });

        low_l.setText("Low level");
        low_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                low_lActionPerformed(evt);
            }
        });

        med_l.setText("Medium level");
        med_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_lActionPerformed(evt);
            }
        });

        high_l.setText("High level");
        high_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                high_lActionPerformed(evt);
            }
        });

        get_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_questionActionPerformed(evt);
            }
        });

        jLabel3.setText("* Enter the Question:");

        ansopt.setText("* Enter correct Answer:");

        get_opt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_opt1ActionPerformed(evt);
            }
        });

        opt1_label.setText("* Enter Option1 :");

        get_opt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_opt2ActionPerformed(evt);
            }
        });

        opt2_label.setText("* Enter Option2 :");

        opt3_label.setText("* Enter Option3 :");

        get_opt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_opt3ActionPerformed(evt);
            }
        });

        opt4_label.setText("* Enter Option4 :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(low_l))
                            .addComponent(Leveldiff)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(get_opt4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(submit_ques)
                                .addGap(10, 10, 10)))
                        .addGap(75, 75, 75))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(opt1_label)
                            .addComponent(jLabel3)
                            .addComponent(opt4_label)
                            .addComponent(opt2_label)
                            .addComponent(opt3_label)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ansopt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(opt1))
                                    .addComponent(opt3))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(opt2)
                                    .addComponent(opt4)))
                            .addComponent(get_question, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                            .addComponent(get_opt1)
                            .addComponent(get_opt2)
                            .addComponent(get_opt3))
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(med_l, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(high_l))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Qid_label)
                                .addGap(120, 120, 120))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_qid, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Leveldiff)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(low_l)
                            .addComponent(Qid_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_qid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med_l))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(high_l)))
                .addGap(8, 8, 8)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(get_question, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ansopt, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opt1)
                    .addComponent(opt2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt3)
                    .addComponent(opt4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt1_label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(get_opt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt2_label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(get_opt2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt3_label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(get_opt3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt4_label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(get_opt4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submit_ques)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void get_opt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_opt4ActionPerformed
        option4 = get_opt4.getText();
    }//GEN-LAST:event_get_opt4ActionPerformed


    private void submit_quesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_quesActionPerformed

        AddData();
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to submit ?", "Submit", JOptionPane.YES_NO_OPTION, EXIT_ON_CLOSE);
        if (choice == JOptionPane.YES_OPTION) {
            if (checkall()) {
                addtoques();
                reset();
                JOptionPane.showMessageDialog(this, "Question added!");
            } else {
                JOptionPane.showMessageDialog(this, "Error!\nPleases enter all fields !!");
            }
        }

    }//GEN-LAST:event_submit_quesActionPerformed


    private void get_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_questionActionPerformed
        question = get_question.getText();
    }//GEN-LAST:event_get_questionActionPerformed

    private void get_opt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_opt1ActionPerformed
        option1 = get_opt1.getText();
    }//GEN-LAST:event_get_opt1ActionPerformed

    private void get_opt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_opt2ActionPerformed
        option2 = get_opt2.getText();
    }//GEN-LAST:event_get_opt2ActionPerformed

    private void get_opt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_opt3ActionPerformed
        option3 = get_opt3.getText();
    }//GEN-LAST:event_get_opt3ActionPerformed

    private void opt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4ActionPerformed
        ans = 4;
    }//GEN-LAST:event_opt4ActionPerformed

    private void opt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1ActionPerformed
        ans = 1;
    }//GEN-LAST:event_opt1ActionPerformed

    private void opt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2ActionPerformed
        ans = 2;
    }//GEN-LAST:event_opt2ActionPerformed

    private void opt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3ActionPerformed
        ans = 3;
    }//GEN-LAST:event_opt3ActionPerformed

    private void low_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_low_lActionPerformed
        diff_level = 1;
    }//GEN-LAST:event_low_lActionPerformed

    private void med_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_lActionPerformed
        diff_level = 2;
    }//GEN-LAST:event_med_lActionPerformed

    private void high_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_high_lActionPerformed
        diff_level = 3;
    }//GEN-LAST:event_high_lActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Leveldiff;
    private javax.swing.JLabel Qid_label;
    private javax.swing.JLabel ansopt;
    private javax.swing.JTextField get_opt1;
    private javax.swing.JTextField get_opt2;
    private javax.swing.JTextField get_opt3;
    private javax.swing.JTextField get_opt4;
    private javax.swing.JTextField get_question;
    private javax.swing.JRadioButton high_l;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_qid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton low_l;
    private javax.swing.JRadioButton med_l;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JLabel opt1_label;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JLabel opt2_label;
    private javax.swing.JRadioButton opt3;
    private javax.swing.JLabel opt3_label;
    private javax.swing.JRadioButton opt4;
    private javax.swing.JLabel opt4_label;
    private javax.swing.JButton submit_ques;
    // End of variables declaration//GEN-END:variables
}
