/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author aditya
 */
public class Admin extends javax.swing.JInternalFrame {

    private static int openFrameCount = 0;
    private BufferedImage img;
    private JDesktopPane DesktopPaneAdmin = new JDesktopPane();

    /**
     * Creates new form All
     */
    public Admin() {
        try {
            img = ImageIO.read(getClass().getResourceAsStream("/icons/adminback.jpg"));
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        // A specialized layered pane to be used with JInternalFrames
        DesktopPaneAdmin = new JDesktopPane() {
            @Override
            protected void paintComponent(Graphics grphcs) {
                super.paintComponent(grphcs);
                grphcs.drawImage(img, 0, 0, null);
            }

            @Override
            public Dimension getPreferredSize() {
                return new Dimension(img.getWidth(), img.getHeight());
            }
        };
        setSize(800, 625);
        add(DesktopPaneAdmin);
        DesktopPaneAdmin.setBounds(0, 0, this.getWidth(), this.getHeight());
        DesktopPaneAdmin.setVisible(true);
        initComponents();

    }

    private void addSet(JInternalFrame InternalFrame) {

        JInternalFrame[] allFrames = DesktopPaneAdmin.getAllFrames();
        for (JInternalFrame allFrame : allFrames) {
            DesktopPaneAdmin.remove(allFrame);
        }

        BasicInternalFrameTitlePane titleres = (BasicInternalFrameTitlePane) ((BasicInternalFrameUI) InternalFrame.getUI()).getNorthPane();
        InternalFrame.remove(titleres);
        InternalFrame.setBounds(0, 0, InternalFrame.getWidth(), InternalFrame.getHeight());
        DesktopPaneAdmin.add(InternalFrame);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskpanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        userman = new javax.swing.JMenu();
        viewuser = new javax.swing.JMenuItem();
        adduser = new javax.swing.JMenuItem();
        JMenuItem_setTimeQuestion = new javax.swing.JMenu();
        Viewques = new javax.swing.JMenuItem();
        addques = new javax.swing.JMenuItem();
        setman = new javax.swing.JMenu();
        viewpapers = new javax.swing.JMenuItem();
        addset = new javax.swing.JMenuItem();
        re = new javax.swing.JMenu();
        results = new javax.swing.JMenuItem();
        closingOptions = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();

        setBackground(java.awt.Color.lightGray);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        javax.swing.GroupLayout deskpanelLayout = new javax.swing.GroupLayout(deskpanel);
        deskpanel.setLayout(deskpanelLayout);
        deskpanelLayout.setHorizontalGroup(
            deskpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        deskpanelLayout.setVerticalGroup(
            deskpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        userman.setText("User Mangement");

        viewuser.setText("View/Edit User");
        viewuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewuserActionPerformed(evt);
            }
        });
        userman.add(viewuser);

        adduser.setText("Add User");
        adduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserActionPerformed(evt);
            }
        });
        userman.add(adduser);

        jMenuBar1.add(userman);

        JMenuItem_setTimeQuestion.setText("Question Management");

        Viewques.setText("View/Edit Questions");
        Viewques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewquesActionPerformed(evt);
            }
        });
        JMenuItem_setTimeQuestion.add(Viewques);

        addques.setText("Add Questions");
        addques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addquesActionPerformed(evt);
            }
        });
        JMenuItem_setTimeQuestion.add(addques);

        jMenuBar1.add(JMenuItem_setTimeQuestion);

        setman.setText("Set Exam");

        viewpapers.setText("View/EditPapers");
        viewpapers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpapersActionPerformed(evt);
            }
        });
        setman.add(viewpapers);

        addset.setText("Add Paper");
        addset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsetActionPerformed(evt);
            }
        });
        setman.add(addset);

        jMenuBar1.add(setman);

        re.setText("Result");

        results.setText("Result");
        results.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsActionPerformed(evt);
            }
        });
        re.add(results);

        jMenuBar1.add(re);

        closingOptions.setText("Close");

        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        closingOptions.add(logoutMenuItem);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        closingOptions.add(exit);

        jMenuBar1.add(closingOptions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewuserActionPerformed
        ViewUser viewUser = new ViewUser();
        viewUser.setVisible(true);
        addSet(viewUser);
    }//GEN-LAST:event_viewuserActionPerformed

    private void adduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserActionPerformed
        AddUser addUser = new AddUser();
        addUser.setVisible(true);
        addSet(addUser);
    }//GEN-LAST:event_adduserActionPerformed

    private void ViewquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewquesActionPerformed
        ViewQues viewQues = new ViewQues();
        viewQues.setVisible(true);
        addSet(viewQues);
        viewQues.settable();
    }//GEN-LAST:event_ViewquesActionPerformed

    private void addquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addquesActionPerformed
        AddQues addQues = new AddQues();
        addQues.setVisible(true);
        addSet(addQues);
    }//GEN-LAST:event_addquesActionPerformed

    private void viewpapersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpapersActionPerformed
        ViewPapers viewset = new ViewPapers();
        viewset.setVisible(true);
        addSet(viewset);
        viewset.settable();
    }//GEN-LAST:event_viewpapersActionPerformed

    private void addsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsetActionPerformed
        AddPaper addpaper = new AddPaper();
        addpaper.setVisible(true);
        addpaper.reset();
        addSet(addpaper);
    }//GEN-LAST:event_addsetActionPerformed

    private void resultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsActionPerformed
        Result result = new Result();
        result.setVisible(true);
        addSet(result);
        result.settable();
    }//GEN-LAST:event_resultsActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout ?", "Logout", JOptionPane.YES_NO_OPTION, EXIT_ON_CLOSE);

        if (choice == JOptionPane.YES_OPTION) {
            ApplicationRunner.getMainFrame().doLogin();//calling function to add login screen and remove any ther Internal present on dersktop pane
            setVisible(false);//set admin false
            dispose();//disposing

        }
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit ?", "Exit", JOptionPane.YES_NO_OPTION, EXIT_ON_CLOSE);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuItem_setTimeQuestion;
    private javax.swing.JMenuItem Viewques;
    private javax.swing.JMenuItem addques;
    private javax.swing.JMenuItem addset;
    private javax.swing.JMenuItem adduser;
    private javax.swing.JMenu closingOptions;
    private javax.swing.JPanel deskpanel;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenu re;
    private javax.swing.JMenuItem results;
    private javax.swing.JMenu setman;
    private javax.swing.JMenu userman;
    private javax.swing.JMenuItem viewpapers;
    private javax.swing.JMenuItem viewuser;
    // End of variables declaration//GEN-END:variables
}
